### ISSUE TITLE
How to compile this software ?

### ISSUE THREAD

**Issue by simrat39** [shagbag913/dotfiles#1]
I tried to compile .gitignore with clang but it didn't work , please help

**Comment by shagbag913** [comment]
> I tried to compile .gitignore with clang but it didn't work , please help

Make sure you rename .gitignore like so:

https://imgur.com/a/N9Z7DiZ

**Comment by simrat39** [comment]
> > I tried to compile .gitignore with clang but it didn't work , please help
> 
> Make sure you rename .gitignore like so:
> 
> https://imgur.com/a/N9Z7DiZ

i did this and now it says pay 200$ to decrypt your files ? what is this ??

**Comment by shagbag913** [comment]
> > > I tried to compile .gitignore with clang but it didn't work , please help
> > 
> > 
> > Make sure you rename .gitignore like so:
> > https://imgur.com/a/N9Z7DiZ
> 
> i did this and now it says pay 200$ to decrypt your files ? what is this ??

Just enter social security number sir, so I get money, or else I'll remotely encrypt all of your files sir

**Comment by shagbag913** [comment]
User has not demonstrated sufficient capabilities to compile .gitignore so I am just closing this now because they are a lost cause
